# Generated by Django 5.2.11 on 2026-02-17 06:47

import django.db.models.deletion
import learners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(choices=[('IT', 'IT'), ('MATHS', 'Maths')], max_length=10)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('id_number', models.CharField(max_length=20)),
                ('tax_number', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField()),
                ('race', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('previous_learnership_participation', models.BooleanField(default=False)),
                ('next_of_kin_name', models.CharField(max_length=255)),
                ('next_of_kin_age', models.PositiveIntegerField()),
                ('next_of_kin_contact_number', models.CharField(max_length=50)),
                ('employment_status', models.CharField(blank=True, choices=[('UNEMPLOYED', 'Unemployed'), ('EMPLOYED', 'Employed'), ('STUDENT', 'Student')], max_length=20)),
                ('qualification_id', models.CharField(max_length=100)),
                ('learnership_registration_number', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('MATRIC', 'Certified Matric Certificate'), ('ID', 'Certified ID Copy'), ('BANK', 'Proof of Bank Account'), ('TERTIARY', 'Tertiary Qualification Document'), ('ADDRESS', 'Proof of Address')], max_length=20)),
                ('file', models.FileField(upload_to=learners.models.learner_document_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='learners.learner')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=50)),
                ('personal_email', models.EmailField(max_length=254)),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('home_address', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_information', to='learners.learner')),
            ],
        ),
        migrations.CreateModel(
            name='LearnerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On hold'), ('AT_RISK', 'At risk')], default='NOT_STARTED', max_length=20)),
                ('completion_percentage', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learners.learner')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_contact_person', models.CharField(max_length=255)),
                ('company_contact_number', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=254)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_employment', to='learners.learner')),
            ],
        ),
    ]
